### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by suoyukii**
Added tags

### CODE REVIEW

**Comment by 4nyNoob** [comment]
the mod is also avaliable in modrinth: https://modrinth.com/mod/miku-plushies/

and by the way, thank you so much for the engagement and support to the project :D

**Comment by suoyukii** [comment]
Changed.

image

**Comment by 4nyNoob** [comment]
i forgot to merge this earlier, I'm sorry :(
but again, thank you very much for the support :D

**Comment by 4nyNoob** [comment]
@suoyukii hey, i've been working on a new update for the mod and I'd like to release the translations in the main release of the mod if possible, where can i contact you directly?

**Comment by suoyukii** [comment]
@4nyNoob Just @ me directly.

**Pull request merged**
