### PR TITLE
Create zh_cn.json

### PR DESCRIPTION
**Pull request by suoyukii**

### CODE REVIEW

**Comment by 4nyNoob** [comment]
thank you so much for translating my mod to Chinese :smile: 

everything looks amazing aside from a couple of things that _I'm not sure if these are indeed incorrect because i'm using google translate to verify the translation_, but using the english translation as a reference there are some small errors on the meaning:
 - **Pará Miku Plush** is referring to the Brazilian state Pará
 - **Amazonas Miku Plush** is supposed to be referring to the Brazilian state Amazonas, and not the Amazon rainforest
 - **Hatsune Mushmiku Plush** Mushmiku is supposed to be a mix of the words mushroom + miku
 - **Gaúcha Miku Plush** is supposed to be in female, but i don't know if chinese does have a male plus female version of some words like we do in PT-BR
 
 if google translate is playing a trick on me and creating these errors out of thin air i believe that it's ready to be merged, and also thank you so much for the contribution once again :smile:

**Comment by suoyukii** [comment]
It is recommended to use `Deepl` for translation as it is more accurate.

- In Chinese, it is possible to omit the adjective of place of residence, but only if it is said in the country in which it is located or if there is a declaration in advance as to which country it is.
  - `帕拉州` and `帕拉` have the same meaning when the conditions are met.
- Amazon's translation is correct as Amazon Rainforest has a special translation, see below:
  - https://baike.baidu.com/item/%E4%BA%9A%E9%A9%AC%E9%80%8A%E7%83%AD%E5%B8%A6%E9%9B%A8%E6%9E%97
  - At the introduction.
- The translation of `Hatsune Mushmiku Plush` is indeed wrong.
- I have searched the internet for the word `Gaúcha`, the name of a TV station and an ethnic race and culture.
  - I searched for information about this ethnic race and it's location is being in Brazil, so it highly matches the translation .
  - If the word is a person's name it probably can't be translated.

Translation from DeepL.

**Comment by suoyukii** [comment]
I've fixed the problematic translation.

**Comment by 4nyNoob** [comment]
i've just updated the mod with some more mikus 😃

**Comment by suoyukii** [comment]
The new translation has been translated.

Is `Senbonzakura Miku` missing `Plush` in the `en_us.json` file?

**Pull request merged**
